In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',


]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
## One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr


[[5736, 1620, 4391, 3707],
 [5736, 1620, 4391, 4513],
 [5736, 7909, 4391, 8051],
 [1881, 1257, 8315, 2185, 8128],
 [1881, 1257, 8315, 2185, 4030],
 [9233, 5736, 7661, 4391, 3745],
 [9370, 8634, 712, 2185]]

In [6]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5736 1620 4391 3707]
 [   0    0    0    0 5736 1620 4391 4513]
 [   0    0    0    0 5736 7909 4391 8051]
 [   0    0    0 1881 1257 8315 2185 8128]
 [   0    0    0 1881 1257 8315 2185 4030]
 [   0    0    0 9233 5736 7661 4391 3745]
 [   0    0    0    0 9370 8634  712 2185]]


In [18]:
## feature representation\
dim=10


In [19]:


model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


In [20]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[[-2.97168028e-02, -4.80161086e-02,  4.38302644e-02,
         -1.22457854e-02,  8.06667656e-03,  4.75222357e-02,
          8.51255655e-03, -3.43542248e-02,  6.59192726e-03,
          2.91373990e-02],
        [-2.97168028e-02, -4.80161086e-02,  4.38302644e-02,
         -1.22457854e-02,  8.06667656e-03,  4.75222357e-02,
          8.51255655e-03, -3.43542248e-02,  6.59192726e-03,
          2.91373990e-02],
        [-2.97168028e-02, -4.80161086e-02,  4.38302644e-02,
         -1.22457854e-02,  8.06667656e-03,  4.75222357e-02,
          8.51255655e-03, -3.43542248e-02,  6.59192726e-03,
          2.91373990e-02],
        [-2.97168028e-02, -4.80161086e-02,  4.38302644e-02,
         -1.22457854e-02,  8.06667656e-03,  4.75222357e-02,
          8.51255655e-03, -3.43542248e-02,  6.59192726e-03,
          2.91373990e-02],
        [-2.13972479e-03,  3.81231047e-02, -2.18874216e-03,
         -2.09985506e-02,  1.78453214e-02, -2.76802182e-02,
         -2.94952746e-02, -3.27446461e-02, -1.278170

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 5736, 1620, 4391, 3707])